import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Users, GraduationCap, DollarSign, CalendarCheck, ArrowUpRight, CheckCircle } from "lucide-react";
export const DashboardView = ({ userRole }) => {
    const stats = [
        { label: "Total Enrolled Students", value: "3,842", change: "+12.4%", icon: GraduationCap, color: "text-blue-600", bg: "bg-blue-50" },
        { label: "Faculty & Staff Members", value: "248", change: "+4.1%", icon: Users, color: "text-indigo-600", bg: "bg-indigo-50" },
        { label: "Fee Collection (YTD)", value: "₹12.85 Cr", change: "94.8%", icon: DollarSign, color: "text-emerald-600", bg: "bg-emerald-50" },
        { label: "Campus Attendance Rate", value: "94.2%", change: "+1.8%", icon: CalendarCheck, color: "text-cyan-600", bg: "bg-cyan-50" },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-gradient-to-r from-sky-700 via-sky-800 to-indigo-900 rounded-2xl p-6 text-white shadow flex flex-col md:flex-row justify-between items-start md:items-center gap-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "inline-flex items-center space-x-2 px-2.5 py-1 rounded-full bg-white/10 text-sky-200 text-xs font-medium mb-2", children: [_jsx("span", { children: "Academic Year 2026-2027" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "Semester 4 Live" })] }), _jsx("h1", { className: "text-2xl font-bold", children: "Apex Institute of Technology & Management" }), _jsx("p", { className: "text-sky-100 text-xs mt-1", children: "Autonomous University System \u2022 NAAC A++ Accredited" })] }), _jsxs("div", { className: "bg-white/10 px-4 py-3 rounded-xl text-right", children: [_jsx("div", { className: "text-xs text-sky-200", children: "System Security & Compliance" }), _jsxs("div", { className: "text-sm font-bold text-emerald-300 flex items-center justify-end space-x-1.5 mt-0.5", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-emerald-400" }), _jsx("span", { children: "100% Audit Verified" })] })] })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4", children: stats.map((s, idx) => {
                    const Icon = s.icon;
                    return (_jsxs("div", { className: "bg-white rounded-xl p-5 border border-slate-200 shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: `p-2.5 rounded-lg ${s.bg}`, children: _jsx(Icon, { className: `w-5 h-5 ${s.color}` }) }), _jsxs("span", { className: "text-xs font-semibold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full flex items-center", children: [_jsx(ArrowUpRight, { className: "w-3 h-3 mr-0.5" }), s.change] })] }), _jsxs("div", { className: "mt-3", children: [_jsx("div", { className: "text-2xl font-extrabold text-slate-800", children: s.value }), _jsx("div", { className: "text-xs text-slate-500 mt-0.5 font-medium", children: s.label })] })] }, idx));
                }) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "lg:col-span-2 bg-white rounded-xl p-5 border border-slate-200 shadow-sm space-y-4", children: [_jsx("h3", { className: "font-bold text-sm text-slate-800 border-b border-slate-100 pb-3", children: "Live Campus Operations & Academic Status" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-3", children: [_jsxs("div", { className: "p-3.5 rounded-lg bg-slate-50 border border-slate-200", children: [_jsx("div", { className: "text-xs font-semibold text-slate-700", children: "Today's Class Schedule (CS Dept)" }), _jsx("div", { className: "text-xs text-slate-500 mt-1", children: "CS401: Distributed Systems (RM-101)" }), _jsxs("div", { className: "mt-2 flex items-center justify-between text-[11px]", children: [_jsx("span", { className: "text-emerald-700 font-bold bg-emerald-100 px-2 py-0.5 rounded", children: "Attendance: 94.2%" }), _jsx("span", { className: "text-slate-400", children: "09:00 - 10:00 AM" })] })] }), _jsxs("div", { className: "p-3.5 rounded-lg bg-slate-50 border border-slate-200", children: [_jsx("div", { className: "text-xs font-semibold text-slate-700", children: "Campus Transport Fleet" }), _jsx("div", { className: "text-xs text-slate-500 mt-1", children: "12 Buses On Route \u2022 GPS Live" }), _jsxs("div", { className: "mt-2 flex items-center justify-between text-[11px]", children: [_jsx("span", { className: "text-sky-700 font-bold bg-sky-100 px-2 py-0.5 rounded", children: "All Routes On Time" }), _jsx("span", { className: "text-slate-400", children: "ETA: 08:45 AM" })] })] })] })] }), _jsxs("div", { className: "bg-white rounded-xl p-5 border border-slate-200 shadow-sm space-y-4", children: [_jsx("h3", { className: "font-bold text-sm text-slate-800 border-b border-slate-100 pb-3", children: "AI Predictive Insights" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "p-3 rounded-lg bg-indigo-50 border border-indigo-100", children: [_jsx("div", { className: "text-xs font-bold text-indigo-950", children: "Student Dropout Risk: Minimal (1.6%)" }), _jsx("p", { className: "text-[11px] text-slate-600 mt-1", children: "Retention model indicates optimal engagement across all engineering branches." })] }), _jsxs("div", { className: "p-3 rounded-lg bg-emerald-50 border border-emerald-100", children: [_jsx("div", { className: "text-xs font-bold text-emerald-950", children: "Fee Collection Forecast: 94.8%" }), _jsx("p", { className: "text-[11px] text-slate-600 mt-1", children: "Automated reminders projected to collect remaining dues smoothly." })] })] })] })] })] }));
};
