"""
Organization Domain Value Objects.
"""
from enum import Enum

class InstitutionType(str, Enum):
    SCHOOL = "SCHOOL"
    COLLEGE = "COLLEGE"
    UNIVERSITY = "UNIVERSITY"
    AFFILIATED_COLLEGE = "AFFILIATED_COLLEGE"
    POLYTECHNIC = "POLYTECHNIC"

class RoomType(str, Enum):
    CLASSROOM = "CLASSROOM"
    LABORATORY = "LABORATORY"
    LECTURE_HALL = "LECTURE_HALL"
    SEMINAR_HALL = "SEMINAR_HALL"
    FACULTY_OFFICE = "FACULTY_OFFICE"
    AUDITORIUM = "AUDITORIUM"
    LIBRARY = "LIBRARY"
    STORE_ROOM = "STORE_ROOM"
    CAFETERIA = "CAFETERIA"

class DepartmentType(str, Enum):
    ACADEMIC = "ACADEMIC"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    FINANCE = "FINANCE"
    HUMAN_RESOURCES = "HUMAN_RESOURCES"
    EXAMINATION_CELL = "EXAMINATION_CELL"
    STUDENT_AFFAIRS = "STUDENT_AFFAIRS"
    TRANSPORT = "TRANSPORT"
    HOSTEL = "HOSTEL"
    LIBRARY = "LIBRARY"
    IT_SERVICES = "IT_SERVICES"
    PROCUREMENT = "PROCUREMENT"
