CREATE TABLE IF NOT EXISTS erp_students_records (
                id VARCHAR(36) PRIMARY KEY,
                tenant_id VARCHAR(64) NOT NULL,
                user_id VARCHAR(36) REFERENCES erp_identity_users(id),
                admission_number VARCHAR(64) UNIQUE NOT NULL,
                roll_number VARCHAR(64) UNIQUE NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                date_of_birth DATE NOT NULL,
                gender VARCHAR(20) NOT NULL,
                email VARCHAR(255) NOT NULL,
                phone_number VARCHAR(30),
                department_id VARCHAR(64) NOT NULL,
                program_id VARCHAR(64) NOT NULL,
                current_semester INT DEFAULT 1 NOT NULL,
                section VARCHAR(10) DEFAULT 'A' NOT NULL,
                status VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
                blood_group VARCHAR(10),
                address TEXT,
                emergency_contact_name VARCHAR(100),
                emergency_contact_phone VARCHAR(30),
                cgpa NUMERIC(4, 2) DEFAULT 0.0,
                attendance_percentage NUMERIC(5, 2) DEFAULT 0.0,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
